/**
 * ARYANNA MASTER PRO 2026 - Banco de Dados de Estruturas e Espelhos
 */

const SALTO = "\n\n\n\n\n\n\n\n\n\n";
const QUALIF = "nacionalidade..., estado civil..., profissão..., portador da cédula de identidade RG nº..., inscrito no CPF sob o nº..., endereço eletrônico..., residente e domiciliado na...";

export const DATA_MASTER = {
    estruturas: {
        'RT': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}RECLAMANTE, ${QUALIF}, por seu advogado abaixo subscrito, vem propor RECLAMAÇÃO TRABALHISTA (Art. 840, § 1º, da CLT) em face de RECLAMADA, (qualificação), pelos fatos e fundamentos a seguir expostos:\n\nI - PRELIMINARMENTE\na) Justiça Gratuita (Art. 790, §3º CLT);\nb) Tramitação Prioritária (Art. 1.048 CPC);\nc) Antecipação de Tutela (Art. 300 CPC / Art. 273 CLT).\n\nII - DO MÉRITO (Fato, Fundamento e Pedido)\n1. (TÍTULO DO PEDIDO)\nFato: ...\nFundamento: (Artigo/Súmula/OJ) ...\nPedido: Requer a condenação ao pagamento de ...\n\nIII - REQUERIMENTOS FINAIS\na) Notificação da reclamada (Súmula 74 TST);\nb) Produção de provas (documental, testemunhal e pericial);\nc) PROCEDÊNCIA TOTAL com juros e correção;\nd) Honorários de sucumbência de 15% (Art. 791-A da CLT);\ne) Recolhimentos previdenciários e fiscais.\n\nAtribui-se à causa o valor de R$ ...\n\nNestes Termos, Pede Deferimento. Local e Data. Advogado... OAB...`,
        
        'CON': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}Processo nº...\nRECLAMADA, já qualificada, vem apresentar CONTESTAÇÃO (Art. 847 da CLT) em face de NOME DO RECLAMANTE.\n\nI - PRELIMINARES DE MÉRITO (Art. 337 do CPC)\n(Inépcia, Ilegitimidade, Perempção, Litispendência, Coisa Julgada).\n\nII - PREJUDICIAIS DE MÉRITO\n(Prescrição Bienal ou Quinquenal - Art. 7º, XXIX, CF/88).\n\nIII - DO MÉRITO\n(Impugnação específica para cada item - Fato, Fundamento e Pedido de Improcedência).\n\nIV - REQUERIMENTOS FINAIS\na) Acolhimento das preliminares e prejudiciais;\nb) No mérito, a TOTAL IMPROCEDÊNCIA;\nc) Produção de provas;\ d) Honorários de sucumbência (Art. 791-A, §3º CLT).\n\nNestes Termos, Pede Deferimento. Local e Data. Advogado... OAB...`,
        
        'RO': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}Processo nº...\nRECORRENTE, vem interpor RECURSO ORDINÁRIO (Art. 895, I, da CLT) para o Egrégio TRT. Pressupostos de admissibilidade presentes (Tempestividade e Preparo anexos). Requer intimação da parte contrária e remessa ao Tribunal.\n\n----------\n\nRAZÕES DO RECURSO ORDINÁRIO\n\nI - PRELIMINARES/PREJUDICIAIS RECURSAIS\nII - MÉRITO (REFORMA DO JULGADO)\n(Tese: Fato, Fundamento e Pedido de Reforma).\n\nIII - CONCLUSÃO\nRequer o CONHECIMENTO e PROVIMENTO do recurso.\n\nLocal e Data. Advogado... OAB...`,

        'AP': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}Processo nº... (Execução)\nAGRAVANTE, vem interpor AGRAVO DE PETIÇÃO (Art. 897, 'a', da CLT). O Agravante delimita, justificadamente, as matérias e os valores impugnados (Art. 897, § 1º da CLT).\n\n----------\n\nRAZÕES DO AGRAVO DE PETIÇÃO\n\nI - MÉRITO (Reforma na execução).\nII - CONCLUSÃO: Conhecimento e Provimento.`,

        'ACP': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}NOME DO CONSIGNANTE, ${QUALIF}, vem, com fulcro no Art. 539 do CPC e Art. 769 da CLT, propor:\n\nAÇÃO DE CONSIGNAÇÃO EM PAGAMENTO\n\nI - DO DEPÓSITO\nRequer o depósito da quantia/objeto no prazo de 5 dias (Art. 542, I CPC).\n\nII - DO MÉRITO\n(Explicar recusa ou dúvida no pagamento - Art. 544 CPC).\n\nIII - REQUERIMENTOS FINAIS\na) Deferimento do depósito;\nb) Notificação do consignatário para levantar ou contestar;\nc) PROCEDÊNCIA para declarar extinta a obrigação e dar quitação das parcelas;\nd) Honorários.\n\nValor da causa: R$ ...\nNestes Termos, Pede Deferimento.`,
        
        'IAFG': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}NOME DO REQUERENTE, ${QUALIF}, vem, com fulcro no Art. 853 da CLT, propor:\n\nINQUÉRITO PARA APURAÇÃO DE FALTA GRAVE\n\nI - DA SUSPENSÃO (Prazo de 30 dias - Art. 853 CLT).\nII - DO MÉRITO (Falta grave - Art. 482 CLT).\nIII - REQUERIMENTOS FINAIS\na) Notificação do requerido;\nb) Oitiva de até 6 testemunhas (Art. 821 CLT);\nc) Procedência para rescindir o contrato por justa causa.\n\nNestes Termos, Pede Deferimento.`,
        
        'HTE': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}NOME DO REQUERENTE 1 e NOME DO REQUERENTE 2, por seus advogados distintos, vêm, com fulcro no Art. 855-B da CLT, requerer:\n\nHOMOLOGAÇÃO DE TRANSAÇÃO EXTRAJUDICIAL\n\nI - DOS TERMOS (Verbas, valores e prazos).\nII - DOS PEDIDOS\na) Suspensão do prazo prescricional (Art. 855-E CLT);\nb) Homologação por sentença (Título Executivo);\nc) Justiça gratuita.\n\nNestes Termos, Pedem Deferimento.`,
        
        'RR': `AO EXCELENTÍSSIMO SENHOR DOUTOR DESEMBARGADOR PRESIDENTE DO EGRÉGIO TRT DA ... REGIÃO\n\nProcesso nº ...${SALTO}NOME DO RECORRENTE, já qualificado, vem, com fulcro no Art. 896 da CLT, interpor RECURSO DE REVISTA.\n\n----------\n\nRAZÕES DO RECURSO DE REVISTA\n\nI - TRANSCENDÊNCIA (Art. 896-A CLT);\nII - PRESSUPOSTOS INTRÍNSECOS (Divergência ou Violação);\nIII - PREQUESTIONAMENTO (Transcrição do trecho da decisão - Art. 896, §1º-A CLT).\nIV - CONCLUSÃO: Conhecimento e Provimento.`,
        
        'AI': `AO DOUTO JUÍZO DA ...\n\nProcesso nº ...${SALTO}NOME DO AGRAVANTE, já qualificado, vem, com fulcro no Art. 897, 'b' da CLT, interpor AGRAVO DE INSTRUMENTO. Declara a formação do instrumento (Art. 897, § 5º CLT). Preparo recolhido (Art. 899, §7º CLT).\n\n----------\n\nRAZÕES DO AGRAVO DE INSTRUMENTO\n\nI - DA REFORMA (Demonstrar cabimento do recurso destrancado).\nII - CONCLUSÃO: Provimento para processar o recurso denegado.`,
        
        'ED': `AO DOUTO JUÍZO DA ...\n\nProcesso nº ...${SALTO}NOME DA PARTE, já qualificada, vem, com fulcro no Art. 897-A da CLT e Art. 1.022 do CPC, opor:\n\nEMBARGOS DE DECLARAÇÃO\n\nI - CABIMENTO (Omissão, Contradição, Obscuridade ou Erro Material).\nII - RAZÕES e PEDIDO: Sanar o vício com efeito modificativo.`,
        
        'AIN': `AO EXCELENTÍSSIMO SENHOR DOUTOR DESEMBARGADOR RELATOR DO EGRÉGIO TRT DA ... REGIÃO\n\nProcesso nº ...${SALTO}NOME DO AGRAVANTE, vem, com fulcro no Art. 1.021 do CPC, interpor AGRAVO INTERNO.\n\nI - RAZÕES: Impugnação específica dos fundamentos da decisão monocrática.\nII - CONCLUSÃO: Retratação ou Provimento.`,
        
        'CR': `AO DOUTO JUÍZO DA ...\n\nProcesso nº ...${SALTO}NOME DO RECORRIDO, já qualificado, vem, com fulcro no Art. 900 da CLT, apresentar:\n\nCONTRARRAZÕES AO RECURSO (...)\n\nI - MÉRITO: Manutenção da decisão.\nII - CONCLUSÃO: Não provimento do recurso adverso.`,
        
        'EE': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}Processo nº ... (Execução)\nNOME DO EXECUTADO, já qualificado, vem, com fulcro no Art. 884 da CLT, opor:\n\nEMBARGOS À EXECUÇÃO\n\n(Garantia do juízo comprovada).\nI - MÉRITO (Art. 884 CLT).\nII - PEDIDO: Procedência para ajustar a execução.`,
        
        'EPE': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}Processo nº ...\nNOME DO EXECUTADO, vem, com base na Súmula 393 do TST, opor:\n\nEXCEÇÃO DE PRÉ-EXECUTIVIDADE\n\nI - CABIMENTO (Ordem pública - sem garantia do juízo).\nII - MÉRITO E PEDIDO: Extinção da execução.`,
        
        'IDPJ': `AO JUÍZO DA... \n\nProcesso nº ...${SALTO}NOME DO REQUERENTE, vem, com fulcro no Art. 855-A da CLT, suscitar:\n\nINCIDENTE DE DESCONSIDERAÇÃO DA PERSONALIDADE JURÍDICA\n\nI - MÉRITO (Art. 50 CC / Art. 28 CDC).\nII - PEDIDO: Citação dos sócios e suspensão do processo (Art. 134, §3º CPC).`,
        
        'MS': `AO EXCELENTÍSSIMO SENHOR DOUTOR DESEMBARGADOR PRESIDENTE DO EGRÉGIO TRT DA ... REGIÃO${SALTO}NOME DO IMPETRANTE, ${QUALIF}, vem, com fulcro no Art. 5º, LXIX da CF/88 e Lei 12.016/09, impetrar:\n\nMANDADO DE SEGURANÇA COM PEDIDO LIMINAR\n\nI - CABIMENTO (OJ 92 SDI-2).\nII - DA LIMINAR (Fumus boni iuris e Periculum in mora).\nIII - MÉRITO (Direito Líquido e Certo).\nIV - PEDIDOS: Liminar, Notificação da Autoridade Coatora, Ciência ao Órgão de Representação, Oitiva do MPT e Segurança Definitiva.\n\nValor da causa: R$ ...`,
        
        'AR': `AO EXCELENTÍSSIMO SENHOR DOUTOR DESEMBARGADOR PRESIDENTE DO EGRÉGIO TRT DA ... REGIÃO${SALTO}NOME DO AUTOR, ${QUALIF}, vem, com fulcro no Art. 836 da CLT e Art. 966 do CPC, propor:\n\nAÇÃO RESCISÓRIA\n\nI - DEPÓSITO PRÉVIO (20% - Art. 836 CLT).\nII - CABIMENTO (Art. 966 CPC - Trânsito em julgado).\nIII - PEDIDOS: Juízo Rescindente (desconstituição) e Juízo Rescisório (novo julgamento).\n\nValor da causa: R$ ...`,
        
        'ACU': `AO JUÍZO DA... VARA DO TRABALHO DE...${SALTO}NOME DO SINDICATO, substituto processual, vem, com fulcro no Art. 872 da CLT, propor:\n\nAÇÃO DE CUMPRIMENTO\n\nI - MÉRITO (Título Normativo).\nII - PEDIDO: Cumprimento e multa normativa.\n\nValor da causa: R$ ...`
    },
    espelhos: {
        "44": `
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.10" onchange="window.calcNota()"><div class="espelho-txt">Endereçamento: Contestação à 150ª Vara do Trabalho de Manaus [cite: 65]</div><div class="espelho-pt">0.10</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.30" onchange="window.calcNota()"><div class="espelho-txt">Partes: XYZ Ltda, Sandra Pi, Walmir Lé e Reclamante. Art. [cite_start]847 CLT [cite: 65]</div><div class="espelho-pt">0.30</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.40" onchange="window.calcNota()"><div class="espelho-txt">Preliminar: Ilegitimidade passiva sócios (Art. 50 CCB) [cite: 65]</div><div class="espelho-pt">0.40</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.40" onchange="window.calcNota()"><div class="espelho-txt">Preliminar: Inépcia reenquadramento (Art. 330, §1º, I ou 337, IV CPC) [cite: 65]</div><div class="espelho-pt">0.40</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.40" onchange="window.calcNota()"><div class="espelho-txt">Prejudicial: Prescrição parcial (Art. 7, XXIX CF; 11 CLT ou S. 308 TST) [cite: 65]</div><div class="espelho-pt">0.40</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Ticket refeição indevido (Art. 614, §3º CLT) [cite: 65]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Jornada aviso prévio (Art. 488 CLT) [cite: 65]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Periculosidade motocicleta indevida (Art. 193, §4º CLT) [cite: 65]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Reintegração (S. 244, II TST ou Art. 10, II, b ADCT) [cite: 65]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Vale transporte (L. 7418/85 ou D. 10854/21) [cite: 65]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.30" onchange="window.calcNota()"><div class="espelho-txt">Pedidos: Renovação preliminares e extinção sem mérito [cite: 65]</div><div class="espelho-pt">0.30</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.60" onchange="window.calcNota()"><div class="espelho-txt">Pedidos: Prescrição, Improcedência, Provas e Honorários (791-A) [cite: 65]</div><div class="espelho-pt">0.60</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.10" onchange="window.calcNota()"><div class="espelho-txt">Fechamento: Local, data, advogado e OAB [cite: 65]</div><div class="espelho-pt">0.10</div></div>
        `,
        "41": `
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.20" onchange="window.calcNota()"><div class="espelho-txt">Endereçamento: AP p/ 503ª VT/DF e razões ao TRT [cite: 55]</div><div class="espelho-pt">0.20</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.30" onchange="window.calcNota()"><div class="espelho-txt">Partes e Fundamento: Maria Serra/Jeferson Peres; Art. [cite_start]855-A ou 897, a CLT [cite: 55]</div><div class="espelho-pt">0.30</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.20" onchange="window.calcNota()"><div class="espelho-txt">Delimitação justificada: Art. [cite_start]897, §1º CLT [cite: 55]</div><div class="espelho-pt">0.20</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.20" onchange="window.calcNota()"><div class="espelho-txt">Tempestividade: 8 dias. Art. [cite_start]897, caput CLT [cite: 55]</div><div class="espelho-pt">0.20</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.70" onchange="window.calcNota()"><div class="espelho-txt">Tese: IDPJ de ofício vedado (Art. 133 CPC) [cite: 55]</div><div class="espelho-pt">0.70</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.70" onchange="window.calcNota()"><div class="espelho-txt">Tese: Suspensão do processo (Art. 134, §3º CPC ou 855-A, §2º CLT) [cite: 55]</div><div class="espelho-pt">0.70</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.70" onchange="window.calcNota()"><div class="espelho-txt">Tese: Prazo manifestação 15 dias (Art. 135 CPC) [cite: 55]</div><div class="espelho-pt">0.70</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.80" onchange="window.calcNota()"><div class="espelho-txt">Tese: Ilegitimidade (Sócio retirante > 2 anos) Art. [cite_start]10-A CLT ou 1032 CC [cite: 55]</div><div class="espelho-pt">0.80</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.70" onchange="window.calcNota()"><div class="espelho-txt">Tese: Impenhorabilidade aposentadoria (Art. 833, IV ou 529, §3º CPC) [cite: 55]</div><div class="espelho-pt">0.70</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.40" onchange="window.calcNota()"><div class="espelho-txt">Pedidos: Revogação tutela, conhecimento e provimento [cite: 55]</div><div class="espelho-pt">0.40</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.10" onchange="window.calcNota()"><div class="espelho-txt">Fechamento: Local, data, advogado e OAB [cite: 55]</div><div class="espelho-pt">0.10</div></div>
        `,
        "40": `
            <div class="espelho-item"><input type="checkbox" value="0.20" onchange="window.calcNota()"><div class="espelho-txt">Endereçamento: RT p/ VT de Osasco/SP. Art. [cite_start]840, §1 CLT [cite: 44]</div><div class="espelho-pt">0.20</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.20" onchange="window.calcNota()"><div class="espelho-txt">Partes: Espólio Romeu/Julieta e Distribuidora Capuleto [cite: 44]</div><div class="espelho-pt">0.20</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.40" onchange="window.calcNota()"><div class="espelho-txt">Preliminares: Gratuidade e Prioridade (Idosa) Art. [cite_start]1048 CPC [cite: 44]</div><div class="espelho-pt">0.40</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Vínculo empregatício (Art. 3 ou 29 CLT) [cite: 44]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Verbas rescisórias e Multa 477 §8 CLT [cite: 44]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="2.10" onchange="window.calcNota()"><div class="espelho-txt">Dano Material: Enterro, Seguro, Pensão Morte/Mensal (Art. 186/927/948 CCB) [cite: 44]</div><div class="espelho-pt">2.10</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Dano Moral: Acidente Trabalho (223-B CLT ou 186/927 CC) [cite: 44]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.60" onchange="window.calcNota()"><div class="espelho-txt">Honorários (791-A) e Encerramento com valor R$ [cite: 44]</div><div class="espelho-pt">0.60</div></div>
        `,
        "37": `
            <div class="espelho-item"><input type="checkbox" value="0.30" onchange="window.calcNota()"><div class="espelho-txt">Endereçamento: Contestação Jorge Machado 85ª VT/RJ. Art. [cite_start]847 CLT [cite: 24]</div><div class="espelho-pt">0.30</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.60" onchange="window.calcNota()"><div class="espelho-txt">Preliminar: Adiamento audiência (Prazo 5 dias) Art. [cite_start]841 CLT [cite: 24]</div><div class="espelho-pt">0.60</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.60" onchange="window.calcNota()"><div class="espelho-txt">Preliminar: Ilegitimidade ex-sócio (> 2 anos) Art. [cite_start]10-A CLT [cite: 24]</div><div class="espelho-pt">0.60</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.60" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Adicional Transferência (Mudança domicílio) Art. [cite_start]469 CLT [cite: 24]</div><div class="espelho-pt">0.60</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.60" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Horas in itinere (Art. 58, §2º CLT) [cite: 24]</div><div class="espelho-pt">0.60</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.60" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Intervalo Digitador/Acúmulo Função (Art. 72/456 CLT) [cite: 24]</div><div class="espelho-pt">0.60</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="1.00" onchange="window.calcNota()"><div class="espelho-txt">Pedidos: Improcedência, Provas e Honorários (791-A) [cite: 24]</div><div class="espelho-pt">1.00</div></div>
        `,
        "35": `
            <div class="espelho-item"><input type="checkbox" value="0.30" onchange="window.calcNota()"><div class="espelho-txt">Endereçamento: RO p/ 89ª VT Floriano/PI e TRT. Art. [cite_start]895, I CLT [cite: 12]</div><div class="espelho-pt">0.30</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.40" onchange="window.calcNota()"><div class="espelho-txt">Preparo/Tempestividade: 8 dias, custas e depósito [cite: 12]</div><div class="espelho-pt">0.40</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Prescrição Parcial: Instância Ordinária (S. 153 TST ou 193 CC) [cite: 12]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Intervalo Interjornada observado (Art. 66 CLT) [cite: 12]</div><div class="espelho-pt">0.50</div></div>
            <div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Reintegração Indevida (Estabilidade Sindical) Art. [cite_start]543 CLT [cite: 12]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: FGTS Contrato Suspenso (Art. 476 CLT) [cite: 12]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Ajuda Custo/Equiparação Salarial (Art. 457/461 CLT) [cite: 12]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.50" onchange="window.calcNota()"><div class="espelho-txt">Mérito: Insalubridade Reclassificação (Art. 194 CLT) [cite: 12]</div><div class="espelho-pt">0.50</div></div>
            [cite_start]<div class="espelho-item"><input type="checkbox" value="0.80" onchange="window.calcNota()"><div class="espelho-txt">Pedidos: Honorários, Admissibilidade e Reforma [cite: 12]</div><div class="espelho-pt">0.80</div></div>
        `
    }
};
